services:
    a11y-nginx:
        container_name: a11y_nginx
        image: nginx:latest
        ports:
            - "443:443"
        volumes:
            - ./certs:/etc/nginx/certs:ro
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - a11y-nextjs
        restart: unless-stopped
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "3"
    a11y-nextjs:
        container_name: a11y_nextjs
        build:
            context: ./accessibility-front
            dockerfile: ./Dockerfile
        env_file:
            - .env
        environment:
            - API_URL=http://a11y-api:5000
            - JWT_SECRET_KEY=${JWT_SECRET_KEY}
            - NEXT_PUBLIC_BASE_URL=${CLIENT_URL}
            - NEXT_PUBLIC_CAS_URL=${NEXT_PUBLIC_CAS_URL}
            - NEXT_CAS_CLIENT_SAML_TOLERANCE=180000
            - NEXT_CAS_CLIENT_SECRET=${NEXT_CAS_CLIENT_SECRET}
        depends_on:
            a11y-db:
                condition: service_healthy
        restart: unless-stopped
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "3"
    a11y-api:
        container_name: a11y_api
        build:
            context: .
            target: api
        env_file:
            - .env
        environment:
            - FLASK_ENV=${FLASK_ENV}
            - DATABASE_URL=mariadb+mariadbconnector://ally-user:${DB_PASSWORD}@a11y-db:3306/a11y
            - JWT_SECRET_KEY=${JWT_SECRET_KEY}
            - HOSTNAME=${HOSTNAME}
            - CLIENT_URL=${CLIENT_URL}
            - MAIL_SERVER=${MAIL_SERVER}
            - MAIL_PORT=${MAIL_PORT}
            - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
            - SITE_ADMINS=${SITE_ADMINS}
            - ADMIN_EMAIL=${ADMIN_EMAIL}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD}
            - CELERY_BROKER_URL=redis://a11y-redis:6379/0
            - CELERY_RESULT_BACKEND=redis://a11y-redis:6379/0
        depends_on:
            a11y-db:
                condition: service_healthy
        healthcheck:
            test:
                ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "3"
    a11y-db:
        container_name: a11y_db
        image: mariadb:latest
        command:
            - --innodb_page_size=64k
            - --innodb_buffer_pool_size=10G
            - --innodb_log_file_size=256M
            - --innodb_log_group_home_dir=/var/log/mysql
        env_file:
            - .env
        environment:
            - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MARIADB_USER=ally-user
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_DATABASE=a11y
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "mariadb-admin ping -h 127.0.0.1 --silent --user=ally-user --password=${DB_PASSWORD} && mariadb -u ally-user --password=${DB_PASSWORD} -e 'SELECT 1;' a11y",
                ]
            interval: 10s
            timeout: 10s
            retries: 5
        restart: unless-stopped
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "3"
        volumes:
            - a11y_db_data:/var/lib/mysql
            - a11y_db_txlogs:/var/log/mysql
    adminer:
        image: adminer
        environment:
            - ADMINER_DEFAULT_SERVER=a11y-db
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/"]
            interval: 30s
            timeout: 10s
            retries: 3
        ports:
            - 8080:8080
    a11y-redis:
        container_name: a11y_redis
        image: redis:latest
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - a11y-redis-data:/data
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "3"
    a11y-flower:
        container_name: a11y_flower
        build:
            context: .
            target: flower
        ports:
            - "5555:5555"
        environment:
            - CELERY_BROKER_URL=redis://a11y-redis:6379/0
            - CELERY_RESULT_BACKEND=redis://a11y-redis:6379/0
            - FLOWER_BASIC_AUTH=${ADMIN_EMAIL}:${ADMIN_PASSWORD}
        depends_on:
            - a11y-redis
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    'curl -f -u "$$FLOWER_BASIC_AUTH" http://localhost:5555/ || exit 1',
                ]
            interval: 30s
            timeout: 10s
            retries: 5
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "3"
    a11y-worker:
        container_name: a11y_worker
        build:
            context: .
            target: worker
        environment:
            - FLASK_ENV=${FLASK_ENV}
            - DATABASE_URL=mariadb+mariadbconnector://ally-user:${DB_PASSWORD}@a11y-db:3306/a11y
            - CELERY_BROKER_URL=redis://a11y-redis:6379/0
            - CELERY_RESULT_BACKEND=redis://a11y-redis:6379/0
            - JWT_SECRET_KEY=${JWT_SECRET_KEY}
            - API_URL=http://a11y-api:5000
            - CLIENT_URL=${CLIENT_URL}
        depends_on:
            a11y-db:
                condition: service_healthy
            a11y-redis:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "celery", "--app", "celery_app.celery", "status"]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "3"
    a11y-beat:
        container_name: a11y_beat
        build:
            context: .
            target: beat
        environment:
            - FLASK_ENV=${FLASK_ENV}
            - DATABASE_URL=mariadb+mariadbconnector://ally-user:${DB_PASSWORD}@a11y-db:3306/a11y
            - CELERY_BROKER_URL=redis://a11y-redis:6379/0
            - CELERY_RESULT_BACKEND=redis://a11y-redis:6379/0
            - JWT_SECRET_KEY=${JWT_SECRET_KEY}
            - API_URL=http://a11y-api:5000
            - CLIENT_URL=${CLIENT_URL}
        depends_on:
            a11y-db:
                condition: service_healthy
            a11y-redis:
                condition: service_healthy
        restart: unless-stopped
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "3"
volumes:
    a11y-redis-data:
        driver: local
    a11y_db_data:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${NFS_SERVER_IP},rw
            device: :${NFS_SHARE_PATH}/mariadb
    a11y_db_txlogs:
        driver: local
