FROM python:3.12

RUN apt-get update && apt-get install -y

RUN python3 -m pip install --upgrade pip

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY --exclude=./accessibility_front . . 

RUN chmod +x ./scanner.sh


CMD ["./scanner.sh"]