version: "3.8"

services:
    nextjs:
        container_name: a11y_nextjs
        build: ./accessibility-front
        ports:
            - "443:443"
        env_file:
            - .env
        environment:
            - FLASK_ENV=${FLASK_ENV}
            - API_URL=api:5000
            - JWT_SECRET_KEY=${JWT_SECRET_KEY}
        depends_on:
            - db
    api:
        container_name: a11y_api
        build: .
        ports:
            - "5000:5000"
        environment:
            - FLASK_ENV=${FLASK_ENV}
            - DATABASE_URL=postgresql://user:${DB_PASSWORD}@db:5432/mydatabase
            - JWT_SECRET_KEY=${JWT_SECRET_KEY}
            - HOSTNAME=${HOSTNAME}
            - CLIENT_URL=${CLIENT_URL}
            - MAIL_SERVER=${MAIL_SERVER}
            - MAIL_PORT=${MAIL_PORT}
            - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
        depends_on:
            - db
    db:
        container_name: a11y_db
        image: postgres:13
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=a11y
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
        name: a11y_db_data
        driver: local
        driver_opts:
            type: none
            o: addr=${NFS_SERVER_IP},rw
            device: ":${NFS_SERVER_PATH}/a11y"
