"""removed description and impact from check

Revision ID: 21e364c27816
Revises: d62e899ba22f
Create Date: 2025-09-16 13:04:12.556331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e364c27816'
down_revision = 'd62e899ba22f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.drop_column('impact')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('impact', sa.VARCHAR(length=10), nullable=False))

    # ### end Alembic commands ###
