"""added description and website catergories

Revision ID: 4cd16ec09a26
Revises: 5a11fd9aae1c
Create Date: 2025-09-29 12:49:37.632376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd16ec09a26'
down_revision = '5a11fd9aae1c'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('website')]
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        if 'description' not in columns:
            batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        if 'categories' not in columns:
            batch_op.add_column(sa.Column('categories', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('categories')

    # ### end Alembic commands ###
