"""Removed scanning field from website and replaced with current task

Revision ID: 577e27eb3691
Revises: 4cd16ec09a26
Create Date: 2025-10-26 16:13:40.545051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577e27eb3691'
down_revision = '4cd16ec09a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_task_id', sa.String(length=100), nullable=True))
        batch_op.drop_column('scanning')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scanning', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('current_task_id')

    # ### end Alembic commands ###
