"""added admin-users and users to websites

Revision ID: 7cf99568c789
Revises: 9acbef5f7339
Create Date: 2025-09-19 14:10:59.567374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf99568c789'
down_revision = '9acbef5f7339'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    if conn.dialect.name == 'mysql':
        with op.batch_alter_table('site_website_assoc', schema=None) as batch_op:
            batch_op.drop_constraint('fk_site_website', type_='foreignkey')
            batch_op.drop_constraint('fk_site', type_='foreignkey')
            batch_op.create_foreign_key('fk_site_website', 'website', ['website_id'], ['id'], ondelete='CASCADE')
            batch_op.create_foreign_key('fk_site', 'site', ['site_id'], ['id'], ondelete='CASCADE')

        with op.batch_alter_table('user_website_assoc', schema=None) as batch_op:
            batch_op.drop_constraint('fk_user_website', type_='foreignkey')
            batch_op.drop_constraint('fk_user', type_='foreignkey')
            batch_op.create_foreign_key('fk_user_website', 'website', ['website_id'], ['id'], ondelete='CASCADE')
            batch_op.create_foreign_key('fk_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # For SQLite, skip drop_constraint and just create the foreign keys (SQLite does not enforce or name constraints the same way)
    else:
        with op.batch_alter_table('site_website_assoc', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_site_website', 'website', ['website_id'], ['id'], ondelete='CASCADE')
            batch_op.create_foreign_key('fk_site', 'site', ['site_id'], ['id'], ondelete='CASCADE')

        with op.batch_alter_table('user_website_assoc', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_user_website', 'website', ['website_id'], ['id'], ondelete='CASCADE')
            batch_op.create_foreign_key('fk_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.alter_column(new_column_name='admin_id', column_name='user_id')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.alter_column(new_column_name='user_id', column_name='admin_id')

    if conn.dialect.name == 'mysql':
        with op.batch_alter_table('user_website_assoc', schema=None) as batch_op:
            batch_op.drop_constraint('fk_user_website', type_='foreignkey')
            batch_op.drop_constraint('fk_user', type_='foreignkey')
            batch_op.create_foreign_key('fk_user', 'users', ['user_id'], ['id'])
            batch_op.create_foreign_key('fk_user_website', 'website', ['website_id'], ['id'])

        with op.batch_alter_table('site_website_assoc', schema=None) as batch_op:
            batch_op.drop_constraint('fk_site_website', type_='foreignkey')
            batch_op.drop_constraint('fk_site', type_='foreignkey')
            batch_op.create_foreign_key('fk_site_website', 'website', ['website_id'], ['id'])
            batch_op.create_foreign_key('fk_site', 'site', ['site_id'], ['id'])
    else:
        with op.batch_alter_table('user_website_assoc', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_user', 'users', ['user_id'], ['id'])
            batch_op.create_foreign_key('fk_user_website', 'website', ['website_id'], ['id'])

        with op.batch_alter_table('site_website_assoc', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_site_website', 'website', ['website_id'], ['id'])
            batch_op.create_foreign_key('fk_site', 'site', ['site_id'], ['id'])

    # ### end Alembic commands ###
