"""Added error and status to reports

Revision ID: 9acbef5f7339
Revises: 21e364c27816
Create Date: 2025-09-18 10:23:56.003782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9acbef5f7339'
down_revision = '21e364c27816'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('report')]
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        if 'error' not in columns:
            batch_op.add_column(sa.Column('error', sa.String(length=255), nullable=True))
        if 'response_code' not in columns:
            batch_op.add_column(sa.Column('response_code', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('response_code')
        batch_op.drop_column('error')

    # ### end Alembic commands ###
