"""adding rules and checks

Revision ID: d62e899ba22f
Revises: 
Create Date: 2025-09-12 12:12:06.459125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62e899ba22f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('website')]
    with op.batch_alter_table('website', schema=None) as batch_op:
        if 'tags' not in columns:
            batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
